# Generated by Django 5.2.5 on 2025-12-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='graduacao',
            field=models.CharField(choices=[('soldado', 'Soldado'), ('cabo', 'Cabo'), ('3_sargento', '3º Sargento'), ('2_sargento', '2º Sargento'), ('1_sargento', '1º Sargento'), ('subtenente', 'Subtenente'), ('aspirante', 'Aspirante'), ('2_tenente', '2º Tenente'), ('1_tenente', '1º Tenente'), ('capitao', 'Capitão'), ('major', 'Major'), ('tenente_coronel', 'Tenente-Coronel'), ('coronel', 'Coronel'), ('general_brigada', 'General de Brigada'), ('general_divisao', 'General de Divisão'), ('general_exercito', 'General de Exército'), ('marechal', 'Marechal')], max_length=20),
        ),
    ]
